### PR TITLE
docs: updates readme with privatelabeling

### PR DESCRIPTION
**Pull request by mffap**

### CODE REVIEW

**Comment by livio-a** [comment]
Is the gif that short on purpose? It ends when hovering over the primary color

**Comment by mffap** [comment]
> Is the gif that short on purpose? It ends when hovering over the primary color

No, it's messed up! Thanks.

**Comment by fforootd** [comment]
Can we merge this?

**Comment by mffap** [comment]
imo yes, updated the gif

**Review by fforootd — APPROVED** [review]

**Pull request merged**
