### PR TITLE
docs: rate limits

### PR DESCRIPTION
**Pull request by fforootd**

### CODE REVIEW

**Comment by mffap** [comment]
We could add to the policy: 

> To conduct a load test on a shared-cloud or managed instance of our services, you must request to do so with a minimum of 2 weeks notice before the test by contacting us at support@zitadel.ch. You must not conduct load testing without prior approval by us.

**Comment by fforootd** [comment]
Good point. I will integrate such a point into the policy.

**Comment by mffap** [comment]
Suggest to close this PR and handle with #1742

**Comment by fforootd** [comment]
Works with me 👍

**Pull request closed without merging**
