### PR TITLE
docs: fix CAP theorem acronym resolution

### PR DESCRIPTION
**Pull request by zepatrik**
The `P` in `CAP` stands for network partition tolerance (see https://en.wikipedia.org/wiki/CAP_theorem).

Instead of CAP, you might want to refer to [PACELC](https://en.wikipedia.org/wiki/PACELC_theorem) instead, which is more applicable IMO.

### CODE REVIEW

**Comment by fforootd** [comment]
Hey @zepatrik you are absolutely right. It is `partition tolerance`!
I must have slept bad that night 😁 

Regarding PACELC. I will try to rephrase it with that in mind later on 👍

**Review by fforootd — APPROVED** [review]

**Comment by fforootd** [comment]
@zepatrik one other thing, are you interested to exchange some knowledge from IAM to IAM projects 😁 ?

Would be nice to talk to you guys, because we find ory a interesting solution!

**Comment by zepatrik** [comment]
Sure, I forwarded your request and we will reach out to you :e-mail: :wink:

**Comment by fforootd** [comment]
Nice :-)

Florian Forster

C E O

Phone:  +41 79 956 39 01

Web:      www.caos.ch

**Comment by tacurran** [comment]
@fforootd we would be able to set up some time to talk after April 27. Please send me some suggestions to thomas@ory.sh
We look forward to learning more.

**Pull request merged**
