### PR TITLE
chore(translation): suggest different translations

### PR DESCRIPTION
**Pull request by mffap**
suggest to use us-en consistently and use "more correct" version of the German word.

### CODE REVIEW

**Comment by fforootd** [comment]
To start with we decided to use the authorisation as british form of authorization.

As i reread https://www.lexico.com/definition/authorization it is possible to use authorization everywhere 😄 

So, this works with me

**Review by fforootd — APPROVED** [review]

**Comment by fforootd** [comment]
As @MatiMax and I was the only in favor of BE we could easy switch this.

Any objections @caos/zitadel ?

**Comment by MatiMax** [comment]
🤷🏽‍♂️

**Comment by fforootd** [comment]
Well then let's use this from now on

**Pull request merged**
